"""Plugin registry for model backends and feature-specific analyzers."""

from .frozen_checkpoints import (
    FrozenCheckpointRecord,
    find_repo_root,
    frozen_checkpoint_map,
    load_frozen_checkpoint_records,
    local_registry_path,
)
from .model_install import (
    DEFAULT_CLASSES,
    INSTALL_REPORT_SCHEMA,
    RESERVED_MODEL_IDS,
    STAGE_DIRECTORIES,
    SUPPORTED_CHECKPOINT_SUFFIXES,
    CheckpointIntrospection,
    InstalledModelStatus,
    ModelInstallRequest,
    ModelInstallResult,
    ModelUninstallResult,
    inspect_checkpoint,
    install_model,
    local_registry_entries,
    model_catalog_status,
    sha256_file,
    uninstall_model,
    verify_checkpoint_runtime,
    write_install_report,
)
from .registry_validation import (
    RegistryValidationReport,
    validate_frozen_registry,
    write_registry_validation_report,
)
from .pretrained_weights import (
    PRETRAINED_REGISTRY_SCHEMA,
    PretrainedRegistryValidationReport,
    PretrainedWeightRecord,
    load_pretrained_weight_records,
    pretrained_registry_path,
    pretrained_weight_map,
    pretrained_weights_root,
    resolve_bundle_paths,
    resolve_pretrained_record,
    validate_pretrained_registry,
    write_pretrained_validation_report,
)
from .registry import ModelRegistry

__all__ = [
    "DEFAULT_CLASSES",
    "INSTALL_REPORT_SCHEMA",
    "RESERVED_MODEL_IDS",
    "STAGE_DIRECTORIES",
    "SUPPORTED_CHECKPOINT_SUFFIXES",
    "CheckpointIntrospection",
    "FrozenCheckpointRecord",
    "InstalledModelStatus",
    "ModelInstallRequest",
    "ModelInstallResult",
    "ModelRegistry",
    "ModelUninstallResult",
    "PRETRAINED_REGISTRY_SCHEMA",
    "PretrainedRegistryValidationReport",
    "PretrainedWeightRecord",
    "RegistryValidationReport",
    "find_repo_root",
    "inspect_checkpoint",
    "install_model",
    "load_pretrained_weight_records",
    "frozen_checkpoint_map",
    "load_frozen_checkpoint_records",
    "local_registry_entries",
    "local_registry_path",
    "model_catalog_status",
    "pretrained_registry_path",
    "pretrained_weight_map",
    "pretrained_weights_root",
    "resolve_bundle_paths",
    "resolve_pretrained_record",
    "sha256_file",
    "uninstall_model",
    "validate_pretrained_registry",
    "validate_frozen_registry",
    "verify_checkpoint_runtime",
    "write_install_report",
    "write_pretrained_validation_report",
    "write_registry_validation_report",
]
