image_path: test_data/3PB_SRT_data_generation_1817_OD_side1_8.png
model_name: Hydride Conventional
output_dir: outputs/inference
include_analysis: true
enable_gpu: false
device_policy: cpu
params:
  clahe:
    clip_limit: 2.0
    tile_grid_size: [8, 8]
  adaptive:
    block_size: 13
    C: 40
  morph:
    kernel_size: [5, 5]
    iterations: 0
  area_threshold: 95
  crop: false
  crop_percent: 10
